// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaFerrata.Data;

namespace ViaFerrata.Migrations
{
    [DbContext(typeof(ViaFerrataContext))]
    [Migration("20210610155407_NewEntities")]
    partial class NewEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ViaFerrata.Models.Cerinte", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Echipament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varsta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cerinte");
                });

            modelBuilder.Entity("ViaFerrata.Models.Dificultate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dificultate");
                });

            modelBuilder.Entity("ViaFerrata.Models.Experienta", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dificultate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraseeParcurse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varsta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Experienta");
                });

            modelBuilder.Entity("ViaFerrata.Models.Inchiriere", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inchiriere");
                });

            modelBuilder.Entity("ViaFerrata.Models.Traseu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dificultate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeSiLocatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taxa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Traseu");
                });
#pragma warning restore 612, 618
        }
    }
}
