// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaFerrata.Data;

namespace ViaFerrata.Migrations
{
    [DbContext(typeof(ViaFerrataContext))]
    [Migration("20210610143925_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ViaFerrata.Models.Traseu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dificultate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeSiLocatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taxa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Traseu");
                });
#pragma warning restore 612, 618
        }
    }
}
